SELECTION-SCREEN BEGIN OF SCREEN 1001.

*-- log object
SELECTION-SCREEN BEGIN OF BLOCK logobject WITH FRAME TITLE text-s01 NO INTERVALS.

PARAMETER:
  p_obj TYPE balobj_d MEMORY ID balobj MATCHCODE OBJECT bal_daag_subobjresid,
  p_subobj TYPE balsubobj MEMORY ID balsubobj MATCHCODE OBJECT bal_daag_objresid.

SELECTION-SCREEN END OF BLOCK logobject.

*-- tags
SELECTION-SCREEN BEGIN OF BLOCK tags WITH FRAME TITLE text-s04 NO INTERVALS.

SELECT-OPTIONS:
  s_tag FOR gs_selscr-tag.

SELECTION-SCREEN END OF BLOCK tags.

*-- time restrictions
SELECTION-SCREEN BEGIN OF BLOCK time WITH FRAME TITLE text-s02 NO INTERVALS.



SELECTION-SCREEN END OF BLOCK time.

*-- log level
SELECTION-SCREEN BEGIN OF BLOCK loglevel WITH FRAME TITLE text-s03 NO INTERVALS.

PARAMETER:
  p_debug AS CHECKBOX DEFAULT 'X',
  p_fatal AS CHECKBOX DEFAULT 'X',
  p_error AS CHECKBOX DEFAULT 'X',
  p_warn AS CHECKBOX DEFAULT 'X',
  p_info AS CHECKBOX DEFAULT 'X',
  p_user AS CHECKBOX DEFAULT 'X'.

SELECTION-SCREEN END OF BLOCK loglevel.

SELECTION-SCREEN END OF SCREEN 1001.
