INITIALIZATION.

START-OF-SELECTION.
  PERFORM open_gui.

* Hide Execute button from screen
AT SELECTION-SCREEN OUTPUT.
  PERFORM output.


AT SELECTION-SCREEN ON EXIT-COMMAND.
  PERFORM exit.

AT SELECTION-SCREEN.
